CREATE DATABASE notes;
USE notes;
CREATE TABLE users(
    userId INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at DATETIME DEFAULT  CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE notes(
    noteId BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    userId INT UNSIGNED NOT NULL,
    content TEXT NOT NULL,
    created_at DATETIME DEFAULT  CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId)
    REFERENCES users (userId)
    ON DELETE CASCADE
);
